remove 5.2 entry for travis-ci.
php5.2.17 causes conflict with onigurama.

php-mruby/mruby/src/oniguruma.h:646: error: conflicting types for ‘regex_t’/Users/chobie/.phpenv/versions/5.2.17-zts/include/php/regex/regex.h:23: error: previous declaration of ‘regex_t’ was here